version: "3.7"

services:
  postgres:
    restart: always
    image: postgres:11.1
    container_name: mage_api_postgres
    env_file: common_environment.env
    ports:
      - 5432

  mage_api:
    container_name: mage_api
    restart: always
    build:
      context: ./
    volumes:
      # allows auto-reload when code is changed
      - ./:/app
      # allows this container to run docker commands on the host
      - /var/run/docker.sock:/var/run/docker.sock
    # command needs to be overwritten to use auto-reload
    # command: >
    #   sh -c "
    #     uvicorn app.main:app --reload --host 0.0.0.0 --port 80 --log-level info  --log-config ./log_config"
    ports:
      - 80:80
    depends_on:
      - postgres
    env_file: common_environment.env
    environment:
      DEBUG: 1
